language: node_js
node_js:
- '0.12'
notifications:
  email:
  - andygoestohollywood@gmail.com
addons:
  sauce_connect: true
env:
  global:
  - secure: bf0ToN7PE9PMA7khdatAymgolUhNHvTT9HFyjcTLGjjBxkV9lR0qOl80wMSvETaGq3CV+Yw1UDSYAM3qtZ5b4ci1F4rO18wB6bQS2rDJeph1D1Ry2r1+iLIE2HIBMWARrN/OYaMMQXGYyPrBVqWhMAe67VqzqURpnGshqh5UuXnJI3jugvqHyF3qubiOA17wmqA8AAHpal3rdpBNrMeOi3ESjr46ZCQUjLyJksFMo+Dw67E2HTVnVzrLUZFWdk4OeoPSj81YuizWewma2aMLqo5ydqyjcab9befIxXUes7oonJvg2uwNRn9GkoR7C7wsYzrPk7dIL0NoDZetuWlvuwouj2eQgFF0qAMYE0Um1k8txxXh0nbeMWB/RKdIKlM1jVchFN2M6a7eY8VGYgagzJ7mv15/R0eZY4J5bzdX5qgmiWtm64s4K192SzwUSZV8iwHGxnlhD+FtJzbCyvCsvLopYWWIaXBxjiou9Qc11k4FETJXPFW/woMvwSLo4sDWQfI1OcptNYejg1/Dv0z9YdukqU7RxItyF/S4tVhd3sP4PtrJVkw4JVnL7qMdn+kQDU0glKkJabEGJcDZq+THUR2H7CMu2EAiXq46RppqaMfNrCbDgm4yzDYkj7TuAHskLuBugI25E4Ol9eZo6o4vKwyfmtBKiwsDUtD33dXhLGc=
  - secure: Qsoff1CItgt66te6F3LJQG+U8axMZUZQECK6KVLD+cvvPdTmnvkGuW6QatyWlDfxUyFkFeHQNi/bubdwCGYym2excsxF6eOddl5soIVKkT9au6S8kzcuDgwY87kTzRJNot/t1xZIWCt6X3gR+O9f1+AmZugVYbZZSRnwmTRlVq4g3te8OCG//GF94G6GkkNuA5l604vaDcPGVcaX1oaC5m9OFGmqbQBv89gYPVlUsyeXNmpx2qAdZ4pYI6YDCaCKPa8xEIDTozb77ZpStYrq3N7hqkybwipGHiKuNHm711OQArwZq7XcI41d5ddwX4SNPcJVgSJTebM6iLC3WcyQPQxkqTR2HbcjMRPCcMblx5N5r30OfWsh3tPUzR1u0d4AFv8+d3O6HXwlz55THTIfWOru3fiWB0Q5EhGNbbGv1abkvI6A9aNi87+U/GGC30ISoGTx67TYnJZ/LAP6w1jrl0ausExwXM6dkhMa3c/3LCPx0+UCbDEaov42NM0RXebrAcJ/m5gWqJbuq0Eqv7hjz9Q6riD0iQie5hMlqt5PI0owjuYO02paml35cPMp6ZalerSWdDbZGYIjxS3tZByRQoGcoBILzwBWCvBpXDuNpN2u3pHdiHqQmFYaUXEgv4Ukw0iHqVxvPEfo7/XKzQaCz4j9AgtND4h+X4jiQYPJjys=
