language: node_js
node_js:
- '0.12'
notifications:
  email:
  - andygoestohollywood@gmail.com
env:
  global:
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
  - secure: DxGESrn37c6lqbtOqa5AQ92urpRENubC5OXGScpSQuNysEbfMMd2SQYP69iM33bl368K12MaGNCuCDFbRer2n1fheNdon9TmkDSM/L5HQ4yqyx85wikKYlgXxgRT9sItJxlYHZ/SCyh8/aIGmmiAQCy+0c1o+WBbmSIFd9E9A2ifmXKlLJpe1XQzttc7K5uNj9p+INMWKbFIXCu93YrEO3rntHGqiT8OrVSYZinM0uvIqTMlYD5J81OK4oECy8H3CGG1efEldQLGEb6yKD2RuN3wJqHehTK2kRxEnUqZHP5+eJ44KzJGeAmyo+ZXVrLnthJ4EhKWPIfLHwxHZP5kTGqPXU9tOlcUOv5IfSpMH/s1dD4DVXqP5U3u8Jd04XYhWhY5dmb70GEhkWdNG7T/ZCfnXaRotIOmGxy8JLiJqsqnULSE9EcQ8MaZzYPAxgRnGv26Vj0tFn1K1kQCuBvXcwxN+rzkrPqBJJjqtmMHPQksIrT+oQoiCd2bytnvEv9EIdPk/SFqNwpDonlZy5eRphgZGUnhrQ25NU5fzyKtKkU77gcefL3cj8yuP3G5S4ctBiKb3Gbrf3Fv8BAj/T1tHaPyL3aHcWDpxrOMqNeZ0k4F6NeHuL8sq4A01nPx3DBksfBJcmidj5I09eaeaI/Jn3zza/OgFWBVvJ6BBvGZeDM=
  - secure: rJ8ujXCKZEoIC4foY9M/TxRScQZyzX9JD0fzqpR/hn2xqEaqEikoUS2Rj0D592UNBoYCYDCOusOdveJodVF+HNRScH45EX2wh03o3XHRDRTvzEMqR8zaUFZNQ26yAe3qgN/hjOzoo0Nu28tpyxaCWQXl7WhfPLkfXitYSlUf63OVBMau20gx7qckfQ9TgKroHK8cqovkRefRr2BGDGP7MMxkaVpH+JsBfm8KtO6OIQWBtcMgbWwNH5jGXZlOUnwIXCrvUj4v3Va2azH0hqZm2Qn/7zdssUcNi1ijes57ESOYcNQmRL1SBgV925UEEGGEupXZcwlUiJmB6/hXyB6BUJsDPcDA7x8jzsa/wuLjCWOSTROjl5FL2BFMZDxOygEBB6jlv4zREqaL+6b8tvdEfHkvUTJnZ5IfjF1zfg461BlTi/nu1O5g6WQPg+Z5XyO/ZDekrd+0l/C9nnuW/NigBYOMg+EUK6UQCTpB4/M1/JjN1VzDrXRr0i1myLOOXa0h6gkyAQR9YBte7ZEZ+buNwJayRK2Efitsey0o4Z636InGSDAlFXat3jVZ8Sj54vkRSSSjdFMUGl2Nfzf3yuOOD7LKjvgS5pdNeAWEJ8q2KeWfmGNrSl/ak9qw+l2/7OO/oPEHXfVF5muuAVYM24qRgpYsZ60WWtJt2EcBwa0YPio=
script:
  - npm run travis