language: node_js
node_js:
- '0.12'
notifications:
  email:
  - andygoestohollywood@gmail.com
env:
  global:
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
  - secure: DxGESrn37c6lqbtOqa5AQ92urpRENubC5OXGScpSQuNysEbfMMd2SQYP69iM33bl368K12MaGNCuCDFbRer2n1fheNdon9TmkDSM/L5HQ4yqyx85wikKYlgXxgRT9sItJxlYHZ/SCyh8/aIGmmiAQCy+0c1o+WBbmSIFd9E9A2ifmXKlLJpe1XQzttc7K5uNj9p+INMWKbFIXCu93YrEO3rntHGqiT8OrVSYZinM0uvIqTMlYD5J81OK4oECy8H3CGG1efEldQLGEb6yKD2RuN3wJqHehTK2kRxEnUqZHP5+eJ44KzJGeAmyo+ZXVrLnthJ4EhKWPIfLHwxHZP5kTGqPXU9tOlcUOv5IfSpMH/s1dD4DVXqP5U3u8Jd04XYhWhY5dmb70GEhkWdNG7T/ZCfnXaRotIOmGxy8JLiJqsqnULSE9EcQ8MaZzYPAxgRnGv26Vj0tFn1K1kQCuBvXcwxN+rzkrPqBJJjqtmMHPQksIrT+oQoiCd2bytnvEv9EIdPk/SFqNwpDonlZy5eRphgZGUnhrQ25NU5fzyKtKkU77gcefL3cj8yuP3G5S4ctBiKb3Gbrf3Fv8BAj/T1tHaPyL3aHcWDpxrOMqNeZ0k4F6NeHuL8sq4A01nPx3DBksfBJcmidj5I09eaeaI/Jn3zza/OgFWBVvJ6BBvGZeDM=
  - secure: Bn1kG90abIbMULFcTtPGpjyzRSJ45FoBbmbLVbkjEqwXx+6Gu43Q0qUr1+xLUAbcjBbOs9eCFq9LzBOaLiRrwl49n393JZPeL82zq3Ywtx0uOGowj4pj0uNOHpBOBp155Wst9jq8wJwWjKI64i9xrewHJ0xYCvybERWnae7bErrEdg9k/eH62LrkuwtjZwO3X/uOyPzqYtGjHOCnv0g/JvjdVmgUiIyzYf0VGBVqy5IMHLquzqCnFwxqWj4x65MFUMZ9QpqAx5HmSB65IVLYBPJynVCcwL9tMeH6eG3bp1pGThFfecY9Z90s4mD3uvZO3KxOnj9JDT0buQhjUwyZQfQBIBRRaW1It55vEfdPwQnQImLbYProfZ5QW5kG78cFiQa14m8bVfKeoU1ufCD8HTsNzzOtktG91IVbskkmKfj/AHRwGrMSCSmuVZ+XCLeoxGkFXHfNN/RCOlNwHUDplGotCn+MNdb+nb/KcjVYfwwd6MrIicYXPIqn4SRi+nzeFREDjcutI95YsTvqpeOUMNmceo92MhOapzGUQp7Mh0UuRjDipmXJBeKzgeCN/0Krbbe8RFNYXbEoZAgzfHJ0PhWaEe/8GGvIWWrd391vM44Apw9gwt1d/Fet/ZtzHO5X+ejRdPHvlmZ7W8KQzl05eKVJNnolbMQHMK5CvlBNqqQ=
before_script:
- curl https://gist.github.com/mjumbewu/6040423/raw/browserstack_tunnel_setup.sh | bash

script:
- npm run travis
